title: My Personal Site
description: Just a simple personal site with a blog
baseurl: ""
url: "https://z66n.github.io"
theme: null
markdown: kramdown
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post